### ISSUE TITLE
 The color of the teams

### ISSUE THREAD

**Issue by luizfernandonb** [JStalnac/SharpSpades#2]
I was looking at the files on the server and I noticed [this](https://github.com/JStalnac/SharpSpades/blob/master/SharpSpades/Net/Packets/State/StateData.cs) file, and I remembered that teams in AoS can change colors (if I'm not mistaken), and if someone uses this server to host an AoS server, and want to change the colors of the teams, how will it be? The `BlueColor` and `GreenColor` properties explicitly define that the teams are `Blue` and `Green`, wouldn't it be more understandable to change the name of these properties to something more generic? Like for example `Team1` or `Team2`, anyway, this is your choice

**Comment by JStalnac** [comment]
I believe the rationale for the naming was that I didn't like having a number at the end but looking at it now I agree that `Team1` and `Team2` would be better. I'll change it later but now it isn't my biggest interest as I'm trying to get basic functionality working.

**Comment by luizfernandonb** [comment]
> I believe the rationale for the naming was that I didn't like having a number at the end but looking at it now I agree that `Team1` and `Team2` would be better. I'll change it later but now it isn't my biggest interest as I'm trying to get basic functionality working.

Quiet, no problems
