### ISSUE TITLE
classicgen.vxl

### ISSUE THREAD

**Issue by luizfernandonb** [JStalnac/SharpSpades#3]
Could you make this file available in the repository? If so, please provide other files essential for the functioning of the server please, thank you
![image](https://user-images.githubusercontent.com/42288418/118409206-98677f00-b65f-11eb-8a62-c905bb49ed13.png)

**Comment by JStalnac** [comment]
I'm worried of licensing issues so I don't want to include a map file. Any valid AoS map file should work, so feel free to download a map from a site like [aos.party](https://aos.party/).
I've noticed that the ENet binaries are missing and will add them as soon as possible.

**Comment by luizfernandonb** [comment]
> I'm worried of licensing issues so I don't want to include a map file. Any valid AoS map file should work, so feel free to download a map from a site like [aos.party](https://aos.party/).
> I've noticed that the ENet binaries are missing and will add them as soon as possible.

Oh ok, thanks
