### ISSUE TITLE
Unable to load DLL 'libenet'

### ISSUE THREAD

**Issue by luizfernandonb** [JStalnac/SharpSpades#5]
Wouldn't it be better, instead of embedding the DLL in the project, to install the package via NuGet in the project's solution? I would avoid mistakes like this:
![image](https://user-images.githubusercontent.com/42288418/118682938-4b0e1d80-b7d7-11eb-873a-b6a9a43aa0e2.png)

**Comment by JStalnac** [comment]
The included ENet DLL includes a patch (moien007/ENet.Managed#17) that hasn't yet been put into the ENet.Managed NuGet package. If you're missing a native library, include the `ENet.Managed.Runtime` package in the project.
