### ISSUE TITLE
Where is the information about how the AoS server works from?

### ISSUE THREAD

**Issue by luizfernandonb** [JStalnac/SharpSpades#7]
I would like to know if there is any document, any website or something that is written all the information both for the game and the Ace of Spades server, because logically, if you are writing a server in C# for the game, you have to take it out information on how the game works from somewhere, unless you decompile the game and read the source code completely

**Comment by JStalnac** [comment]
The Ace of Spades protocol is documented at https://www.piqueserver.org/aosprotocol/. [piqueserver](https://github.com/piqueserver/piqueserver) and [SpadesX](https://github.com/SpadesX/SpadesX) are good places to look for implementations.
